apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: postgres

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - persistentV.yaml
  - secrets.yaml
  - namespace.yaml

namespace: postgres

images:
- name: postgres
  newTag: latest